version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build: .
    image: "flaskapp"
    ports:
      - "5000:5000"
    depends_on:
      - db